kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: kapacitor
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapacitor-pvc
spec:
  storageClassName: kapacitor
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  ports:
    - port: 9092
      name: kapacitor-api
      targetPort: 9092
  selector:
    app: kapacitor
  type: LoadBalancer
  #loadBalancerIP: "X.X.X.X"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapacitor
  labels:
    app: kapacitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapacitor
  template:
    metadata:
      labels:
        app: kapacitor
    spec:
      containers:
        - image: kapacitor
          name: kapacitor
          env:
          - name: KAPACITOR_INFLUXDB_0_URLS_0
            value: http://influxdb:8086
          volumeMounts:
          - name: kapacitor-volume
            mountPath: /var/lib/kapacitor/
          resources:
            requests:
              memory: "200Mi"
              cpu: "200m"
          ports:
          - name: api
            containerPort: 9092
      volumes:
      - name: kapacitor-volume
        persistentVolumeClaim:
          claimName: kapacitor-pvc
      #nodeSelector:
      #  type: tick
